version: '3.3'

services:
  
  product-launch-db:
    image: microsoft/mssql-server-windows-express
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=d0ck3r_Labs!
    networks:
      - app-net

  product-launch-web:
    image: dockersamples/modernize-aspnet-web:v1
    build: 
      context: ../
      dockerfile: ./docker/web-v1/Dockerfile
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION_STRING=Server=product-launch-db;Database=ProductLaunch;User Id=sa;Password=d0ck3r_Labs!;
    depends_on:
      - product-launch-db
    networks:
      - app-net

networks:
  app-net:
    external: 
     name: nat